---
- hosts: all

  tasks:
  - name: Search windows updates and download them
    ansible.windows.win_updates:
      state: downloaded

  - name: Install all security, critical, and rollup updates, and reboot if needed
    ansible.windows.win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
      skip_optional: yes
      log_path: "C:\\Temp\\update_log{{ ansible_date_time.iso8601_basic_short }}.txt"
      # default is windows update server, uncomment to change to managed update server
      # server_selection: managed_server
      # true if we want to restart
      reboot: true
      reboot_timeout: 3600
    register: dl_updates   